[package]
name = "deduper"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
clap = { version = "3.1.18", features = ["derive"] }
indicatif = "0.16.2"
ansi_term = "0.12.1"